cc_library(  
    name = "custom",  
    srcs = ["custom.cc"],              # 源文件  
    hdrs = ["custom.h"],            # 头文件  
    includes = ["*h"],                     # 头文件搜索路径  
    visibility = ["//visibility:public"],       # 允许其他目标访问  
    linkstatic = False,                        # 指定这是动态库  
)  